import "./globals.css";
import Header from "./_components/header/Header";
import Footer from "./_components/footer/Footer";
import { StyledEngineProvider } from '@mui/material/styles';
export const metadata = {
  title: "Pal Brother's Group",
  description: "Generated by Abhishek Pal",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link href="https://fonts.googleapis.com/css2?family=Hind:wght@300;400;500;600;700&family=Yantramanav:wght@100;300;400;500;700;900&display=swap" rel="stylesheet"></link>
      <body >
        <StyledEngineProvider>
          <Header />
          {children}
          <Footer />
        </StyledEngineProvider>
      </body>
    </html>
  );
}
