import "./globals.css";
import Header from "./_components/header/Header";
import Footer from "./_components/footer/Footer";
import { StyledEngineProvider } from '@mui/material/styles';
export const metadata = {
  title: "Pal Brother's Group",
  description: "Generated by Abhishek Pal",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />

      </head>
      <body >
        <StyledEngineProvider>
          <Header />
          {children}
          <Footer />
        </StyledEngineProvider>
      </body>
    </html>
  );
}
